version: '3'
services:
    mysql5:
        image: mysql:5.7
        container_name: mysql5
        ports:
            - '3306:3306'
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: financeiro
            MYSQL_USER: rubens
            MYSQL_PASSWORD: 123456
