version: '3' # nome  ada  versão

services: # inicia um novo serviço
    db:
        image: postgres
        container_name: postgres

        restart: always
        environment:
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        volumes:
            - ./dados_postgres:/var/lib/postgresql/data
